---
title: "Test interactive file with ShinyApp"
output: html_document
runtime: shiny
---

````{r setup, include=FALSE}
library(knitr)
library(shiny)
library(ggplot2)
library(shinythemes)
library(plotly)

 knitr::opts_chunk$set(echo = FALSE, 
                      eval = TRUE, 
                      message = FALSE,
                      warning = FALSE, 
                      fig.retina = TRUE)
```


````{r app}

# Load data ---------------------------------------------------------------
static <- read.table("spectra_static.txt", header = T, stringsAsFactors = F)[,c("ppm","intensity5")]
colnames(static) <- c("ppm", "intensity")

reactive_1 <- read.table('Hippuric_acid_new.txt', header = T, stringsAsFactors = F)
# default - almost none, intensity1 - huge levels, intensity2 - medium levels

reactive_2 <- read.table('Tartaric_acid_new.txt', header = T, stringsAsFactors = F)
# default - almost none, intensity1 - huge levels, intensity2 - medium levels

reactive_3 <- read.table('L-Carnitine_new.txt', header = T, stringsAsFactors = F)
# default - almost none, intensity1 - huge levels, intensity2 - medium levels

reactive_4 <- read.table('TMAO_new.txt', header = T, stringsAsFactors = F)
# default - almost none, intensity1 - huge levels, intensity2 - medium levels

# Server ------------------------------------------------------------------
# Define server logic required to draw spectra
# Define server logic required to draw spectra
server <- function(input, output) {
  
  #suppressing warnings. for some reason the app was throwing an explicit id warning message. More details:
  # https://github.com/hrbrmstr/metricsgraphics/issues/49
  # options(warn = -1)
  
  make_data <- eventReactive(input$go, {
    runif(input$hippurate)
    if(input$hippurate == 2) {
      reactive_1_s <- data.frame("ppm" = reactive_1[,1], "intensity" = reactive_1[,(4)])
      reactive_2_s <- data.frame("ppm" = reactive_2[,1], "intensity" = reactive_2[,(4)])
      reactive_3_s <- data.frame("ppm" = reactive_3[,1], "intensity" = reactive_3[,(4)])
      reactive_4_s <- data.frame("ppm" = reactive_4[,1], "intensity" = reactive_4[,(4)])
      mkdb <- rbind(static, reactive_1_s, reactive_2_s, reactive_3_s, reactive_4_s)
      # mkdb <- subset(mkdb, ppm >0)
    } else {
      reactive_1_s <- data.frame("ppm" = reactive_1[,1], "intensity" = reactive_1[,(2 + as.numeric(input$hippurate))])
      reactive_2_s <- data.frame("ppm" = reactive_2[,1], "intensity" = reactive_2[,(2 + as.numeric(input$tartrate))])
      reactive_3_s <- data.frame("ppm" = reactive_3[,1], "intensity" = reactive_3[,(2 + as.numeric(input$carnitine))])
      reactive_4_s <- data.frame("ppm" = reactive_4[,1], "intensity" = reactive_4[,(2 + as.numeric(input$tmao))])
      mkdb <- rbind(static, reactive_1_s, reactive_2_s, reactive_3_s, reactive_4_s)
      # mkdb <- subset(mkdb, ppm >0)
    }
  })
  

  output$spectra <- renderPlotly({
    
   p <- ggplot() +
          geom_line(data = make_data(), aes(x=-ppm, y=intensity)) +
          theme_bw() +
          theme(axis.text = element_text(size=12),
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank()) +
          xlab("ppm") +
          scale_x_continuous(breaks = c(0, -2, -4, -6, -8, -10), labels = c(0, 2, 4, 6, 8, 10)) +
          scale_y_continuous(limits = c(0, 150))
    
    ggplotly(p)
    
  })
}




# UI ---------------------------------------------------------------
# Define UI for application that draws spectra
ui <- fluidPage(theme = shinytheme("cerulean"),
                
                # Application title
                titlePanel("What's in your urine?"),
                
                # Sidebar with a slider input for number of bins 
                sidebarLayout(
                  sidebarPanel(
                    p("Describe your meals in the last 24 hours"),
                    selectInput(inputId = "hippurate",
                                label = "How many fruits or vegetables did you have?",
                                c("None, I am a meat-lover" = 0, "Plenty, I live on fruits and vegetables!" = 1, "A single fruit or a small salad" = 2),
                                selected = 2),
                    selectInput(inputId = "tartrate",
                                label = "Did you have any fresh grapes?",
                                c("None" = 0, "More than a handful, grapes are my favourite snack" = 1, "Just a few, I went to a conference buffet lunch" = 2),
                                selected = 2),
                    selectInput(inputId = "carnitine",
                                label = "Did you eat any meat?",
                                c("None, I am a vegetarian" = 0, "A juicy burger for lunch and fried chichen for dinner" = 1, "A healthy portion of lean meat" = 2),
                                selected = 2),
                    selectInput(inputId = "tmao",
                                label = "Did you have any fish or seafood?",
                                c("None" = 0, "A posh platter of seafood" = 1, "Some fish sauce definitely got into my plate" = 2),
                                selected = 2),
                    
                    actionButton("go", "See how it looks!")
                  ),
                  
                  # Show a plot
                  mainPanel(
                    p("Your dietary habits, even those forbidden snacks, can be identified by running your urine sample through an NMR machine.
                      Here is how your urine would likely to look, based on your selected inputs."),
                    
                    plotlyOutput('spectra')
                    
                    # plotOutput("spectra")
                    )
                )
                )


# Create Shiny app ----
shinyApp(ui, server, options = list(width = "100%", height = 550))

```

